### PR TITLE
chore: customize server data return for favicon

### PR DESCRIPTION
**Pull request by eyronjuude**
This PR utilizes a preemptive loading of schema to return a customizable dictionary containing the schema and assets, as well as potential data fields in the future. This PR also unexposes `PUBLIC_APIURL` for asset loads by renaming `+layout.ts` to `+layout.server.ts`.

### CODE REVIEW

**Comment by eyronjuude** [comment]
@VeeIsForVanana right now, for compatibility with respect to our current implementations in the use of schema in `.svelte` files, I curated the return dictionary with each collection as a separate dictionary key.

I want to suggest a much cleaner return for `.svelte` files in which we only use `{ schema, assets } = data` in `{+page, +layout}.svelte` files for loading data to our website, although I am also open for other suggestions about how we style this return dictionary.

For example, instead of:
```svelte
/** @type {import('./$types').LayoutData} */

export let data;

$: ({ global, events, ..., assets } = data);

...

<h1 class="h1">{global.title}</h1>
<p>{global.description}</p>
{#each events as event}
	{@html event.event_content}
{/each}
```
We can use this instead:
```svelte
/** @type {import('./$types').LayoutData} */

export let data;

$: ({ schema, assets } = data);

...

<h1 class="h1">{schema.global.title}</h1>
<p>{schema.global.description}</p>
{#each schema.events as event}
	{@html event.event_content}
{/each}
```

**Comment by eyronjuude** [comment]
@VeeIsForVanana kindly don't merge this yet. I have developed a way to formally unexpose `PUBLIC_APIURL` for favicon, although that requires actual downloading of data using `fetch` and importing `fs` to store the assets in the `static` folder.

**Comment by eyronjuude** [comment]
@VeeIsForVanana I utilized the `fs` module along with a couple changes to the configuration to enable dynamic download of assets, like favicon, to the `/static` folder.

Note that the re-downloading assets _may_ incur performance hits although they only occur upon [reloading the server `load` function](https://svelte.dev/docs/kit/load#Rerunning-load-functions).

I might also add a `url` model in valibot just to make sure that the asset URLs are valid.

**Comment by VeeIsForVanana** [comment]
> @VeeIsForVanana right now, for compatibility with respect to our current implementations in the use of schema in `.svelte` files, I curated the return dictionary with each collection as a separate dictionary key.
> 
> I want to suggest a much cleaner return for `.svelte` files in which we only use `{ schema, assets } = data` in `{+page, +layout}.svelte` files for loading data to our website, although I am also open for other suggestions about how we style this return dictionary.
> 
> For example, instead of:
> 
> `+layout.server.ts`
> 
> ```ts
> return {
> 	global: schema.global,
> 	events: schema.events,
> 	student_council: schema.student_council,
> 	alumni: schema.alumni,
> 	assets: {
> 		favicon: `${PUBLIC_APIURL}/assets/${schema.global.favicon}`
> 	}
> }
> ```
> 
> `+layout.svelte`
> 
> ```svelte
> /** @type {import('./$types').LayoutData} */
> 
> export let data;
> 
> $: ({ global, events, ..., assets } = data);
> 
> ...
> 
> <h1 class="h1">{global.title}</h1>
> <p>{global.description}</p>
> {#each events as event}
> 	{@html event.event_content}
> {/each}
> ```
> 
> We can use this instead:
> 
> `+layout.server.ts`
> 
> ```ts
> return { schema, assets );
> ```
> 
> `+layout.svelte`
> 
> ```svelte
> /** @type {import('./$types').LayoutData} */
> 
> export let data;
> 
> $: ({ schema, assets } = data);
> 
> ...
> 
> <h1 class="h1">{schema.global.title}</h1>
> <p>{schema.global.description}</p>
> {#each schema.events as event}
> 	{@html event.event_content}
> {/each}
> ```

Hi! Apologies for the late response. I don't see any reason not to accept this change, I think it would be a good idea to separate out the schema and asset objects for the layout. Though I do have some slight concerns over how this will look like in individual `+page.server.ts` and `+page.svelte` files, if we're going to adapt a similar `return {schema, assets}` system, since that would mean `schema` would ideally only contain the relevant objects. Though I think we could customize the `schema` validation to make certain fields optional.

**Comment by VeeIsForVanana** [comment]
Relatedly, I'd also like to know if we could merge this PR in yet? Thanks!

**Comment by eyronjuude** [comment]
> > @VeeIsForVanana right now, for compatibility with respect to our current implementations in the use of schema in `.svelte` files, I curated the return dictionary with each collection as a separate dictionary key.
> > I want to suggest a much cleaner return for `.svelte` files in which we only use `{ schema, assets } = data` in `{+page, +layout}.svelte` files for loading data to our website, although I am also open for other suggestions about how we style this return dictionary.
> > ...
> 
> Hi! Apologies for the late response. I don't see any reason not to accept this change, I think it would be a good idea to separate out the schema and asset objects for the layout. Though I do have some slight concerns over how this will look like in individual `+page.server.ts` and `+page.svelte` files, if we're going to adapt a similar `return {schema, assets}` system, since that would mean `schema` would ideally only contain the relevant objects. Though I think we could customize the `schema` validation to make certain fields optional.

Based on [SvelteKit documentation](https://svelte.dev/docs/kit/load#Layout-data), the data returned from `layout.ts` will be inherited by `page.svelte` as well, so don't worry about returned data.

That means we can return all necessary data from `layout.ts` like the entire schema and all asset referencs, and then `page.ts` will only return necessary data like the `global` schema only.

**Comment by eyronjuude** [comment]
> Relatedly, I'd also like to know if we could merge this PR in yet? Thanks!

If it's okay with your code review, I think that's good! I just want to add your review approval in my PRs for sake of cross code checking.

**Review by VeeIsForVanana — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
